import type { Metadata } from 'next';

import feed from '../../../src/lib/data/social-feed.json';
import { SITE_NAME, SITE_URL } from '../../../src/lib/seo';
import { TermPrompt } from '@/shell/TermPrompt';
import { cwdFor } from '@/shell/terminal-path';
import type { Locale } from './posts';

/**
 * The /feed hub for the Next candidate.
 *
 * A template-for-template port of `src/lib/components/SocialFeedPage.svelte`
 * and its two thin route wrappers (`src/routes/feed`, `src/routes/ko/feed`).
 * It renders the sanitized campaign snapshot (`src/lib/data/social-feed.json`,
 * generated by `scripts/snapshot-social.ts`) as campaign cards; all
 * cross-links are computed at build (ADR-053 Phase 6 / social-hub H4).
 *
 * The snapshot is imported from the root package rather than copied: both
 * builds must render the same campaigns, and one file cannot drift from
 * itself. The five `social_feed_*` strings live here as a `copy` table, as
 * `site-shell.tsx` does, because the Paraglide runtime is not resolvable from
 * this package; the values are `messages/en.json:50-54` and
 * `messages/ko.json:50-54` verbatim.
 *
 * V1 of the snapshot is EN-only (campaign topics come from the archive); a
 * `.ko.json` overlay is deferred until KO campaign copy exists (social-hub
 * H3). Both locales therefore render the same campaigns, exactly as the
 * SvelteKit `ko/feed/+page.ts` does.
 *
 * `scripts/assert-feed-redirects.ts` holds this page to the SvelteKit build's
 * page-owned contract: head, header, campaign list, chip attributes and
 * `<html lang>`.
 */

export interface FeedEntry {
	post_id: string;
	date: string;
	platform: string;
	lang: string;
	format: string;
	topic: string;
	url: string;
	is_canonical: boolean;
}

export interface FeedCampaign {
	cluster_id: string | null;
	canonical_url: string | null;
	blog_slug: string | null;
	topic: string;
	date: string;
	entries: FeedEntry[];
}

const COPY = {
	en: {
		title: 'Social feed',
		description:
			'Where each idea went — blog posts, X Articles, and LinkedIn posts grouped by campaign.',
		lede: 'Where each idea went. One campaign, several surfaces — the long-form canonical plus the posts that point at it. Links are computed at build from the publishing archive.',
		empty: 'Nothing published yet.',
		blogPost: 'Blog post',
	},
	ko: {
		title: '소셜 피드',
		description: '캠페인별로 묶은 블로그 글, X Article, LinkedIn 게시물 모음입니다.',
		lede: '하나의 아이디어가 어디에 발행됐는지 보여줍니다. 캠페인 하나와 여러 발행면을 묶고, 긴 글과 그 글을 가리키는 게시물을 함께 연결합니다. 링크는 발행 아카이브에서 빌드 시점에 계산됩니다.',
		empty: '아직 발행된 항목이 없습니다.',
		blogPost: '블로그 글',
	},
} as const;

const PLATFORM_LABEL: Record<string, string> = {
	linkedin: 'LinkedIn',
	x: 'X',
	threads: 'Threads',
	mastodon: 'Mastodon',
	bluesky: 'Bluesky',
};

export function feedPath(locale: Locale): string {
	return locale === 'ko' ? '/ko/feed' : '/feed';
}

export function listFeedCampaigns(): FeedCampaign[] {
	return feed.campaigns;
}

function entryLabel(entry: FeedEntry): string {
	if (entry.platform === 'x' && entry.post_id.endsWith('-x-article')) {
		return 'X Article';
	}
	const platform = PLATFORM_LABEL[entry.platform] ?? entry.platform;
	if (entry.format === 'thread') return `${platform} thread`;
	return platform;
}

function blogHref(slug: string, path: string): string {
	return `${path.startsWith('/ko') ? '/ko' : ''}/posts/${slug}`;
}

/**
 * Head metadata for the feed hub: title, description and canonical only.
 *
 * NOTE: no `alternates.languages` (hreflang) and no `openGraph` block on
 * purpose. The SvelteKit feed pages emit neither — the frozen baseline records
 * `pages["/feed"].alternates = []` and `og = {}` for both locales — so adding
 * them here would be a divergence from the parity oracle, not a fix. Whether
 * the chrome should gain them is a Slice 3 shell decision.
 */
export function generateFeedMetadata(locale: Locale): Metadata {
	const copy = COPY[locale];
	return {
		title: `${copy.title} | ${SITE_NAME}`,
		description: copy.description,
		alternates: {
			canonical: `${SITE_URL}${feedPath(locale)}`,
		},
	};
}

/** A surface row's target column: the href without its scheme. */
function targetText(href: string): string {
	return href.replace(/^https?:\/\//, '');
}

/**
 * The `/feed` (or `/ko/feed`) page body in the Phosphor Fade shell:
 * `cat README` (the `~/feed` crumb, worn h1, lede), then `ls -lt campaigns/`
 * with one frame per campaign whose surfaces are fixed-column rows. Renders
 * inside the site shell's `<main id="main-content">`.
 *
 * PARITY: `scripts/assert-feed-redirects.ts` reads this markup against the
 * Svelte build, so the contract class names stay on the same elements
 * (`crumb`, `feed__lede`, `feed__empty`, `feed__list`, `campaign`,
 * `campaign__id`, `campaign__topic`, `campaign__links`) and each surface is
 * still exactly one `<a class="chip …">` whose text is the label. The row's
 * other columns (tree, `[n]`, lang, fmt, target, canonical mark) are sibling
 * spans outside the anchor; the page styles reach the chips through
 * `.pg-feed .chip`, never through an extra class token on the anchor.
 *
 * @param locale - selects the `COPY` strings, the crumb path and the blog-chip
 *   href prefix; both locales render the same EN-only campaign snapshot
 */
export function SocialFeedPage({ locale }: { locale: Locale }) {
	const copy = COPY[locale];
	const path = feedPath(locale);
	const cwd = cwdFor(path);
	const campaigns = listFeedCampaigns();
	const surfaceCount = campaigns.reduce(
		(sum, campaign) => sum + campaign.entries.length + (campaign.blog_slug ? 1 : 0),
		0,
	);

	// The SvelteKit component owns `<main id="main-content">`; in this package
	// the site shell renders it, so the page is a section inside it. Adjacent
	// text expressions are joined into one string because React's server
	// renderer separates sibling text nodes with `<!-- -->` comments.
	return (
		<section className="feed pg-feed" aria-labelledby="feed-title">
			<header className="feed__head">
				<TermPrompt cwd={cwd} command="cat README" />
				<div className="crumb term-eyebrow">{`~${path}`}</div>
				<div className="term-worn pg-feed__h1">
					<h1 className="feed__title term-ttl" id="feed-title">
						{copy.title}
					</h1>
				</div>
				<p className="feed__lede">{copy.lede}</p>
			</header>

			<div className="term-gap" />
			<TermPrompt cwd={cwd} command="ls -lt campaigns/" />
			<p className="pg-feed__summary" aria-hidden="true">
				{`total ${campaigns.length} · ${surfaceCount}`}
			</p>

			{campaigns.length === 0 ? (
				<p className="feed__empty">{copy.empty}</p>
			) : (
				<ol className="feed__list">
					{campaigns.map((campaign) => {
						const offset = campaign.blog_slug ? 1 : 0;
						const rows = campaign.entries.length + offset;
						const tree = (position: number) => (position === rows - 1 ? '└──' : '├──');
						return (
							<li
								className="campaign term-frame"
								key={campaign.cluster_id ?? campaign.entries[0].post_id}
							>
								<span className="term-frame__title" aria-hidden="true">
									{campaign.cluster_id ?? campaign.date} <span className="dim">{`· ${rows}`}</span>
								</span>
								<div className="campaign__meta">
									<time dateTime={campaign.date}>{campaign.date}</time>
									{campaign.cluster_id ? (
										<>
											<span className="pg-feed__key" aria-hidden="true">
												cluster
											</span>
											<span className="campaign__id">{campaign.cluster_id}</span>
										</>
									) : null}
								</div>
								<h2 className="campaign__topic term-sub">{campaign.topic}</h2>
								<div className="pg-feed__hd" aria-hidden="true">
									<span />
									<span>#</span>
									<span>surface</span>
									<span>lang</span>
									<span>fmt</span>
									<span>target</span>
									<span />
								</div>
								<ul className="campaign__links">
									{campaign.blog_slug ? (
										<li className="pg-feed__row">
											<span className="pg-feed__tr" aria-hidden="true">
												{tree(0)}
											</span>
											<span className="pg-feed__n" aria-hidden="true">
												[b]
											</span>
											<a className="chip chip--blog" href={blogHref(campaign.blog_slug, path)}>
												{copy.blogPost}
											</a>
											<span className="pg-feed__dim" aria-hidden="true">
												{locale}
											</span>
											<span className="pg-feed__dim" aria-hidden="true">
												post
											</span>
											<span className="pg-feed__tgt" aria-hidden="true">
												{blogHref(campaign.blog_slug, path)}
											</span>
											<span />
										</li>
									) : null}
									{campaign.entries.map((entry, index) => {
										const label = `${entryLabel(entry)}${entry.lang !== 'en' ? ` (${entry.lang})` : ''}`;
										return (
											<li
												key={entry.post_id + entry.platform + entry.lang}
												className={entry.is_canonical ? 'pg-feed__row is-canon' : 'pg-feed__row'}
											>
												<span className="pg-feed__tr" aria-hidden="true">
													{tree(index + offset)}
												</span>
												<span className="pg-feed__n" aria-hidden="true">
													{`[${index + 1}]`}
												</span>
												<a
													className={entry.is_canonical ? 'chip chip--canonical' : 'chip'}
													href={entry.url}
													target="_blank"
													rel="noopener noreferrer"
													title={label}
												>
													{label}
												</a>
												<span className="pg-feed__dim" aria-hidden="true">
													{entry.lang}
												</span>
												<span className="pg-feed__dim" aria-hidden="true">
													{entry.format}
												</span>
												<span className="pg-feed__tgt" aria-hidden="true">
													{targetText(entry.url)}
												</span>
												<span className="pg-feed__mk" aria-hidden="true">
													{entry.is_canonical ? '*' : ''}
												</span>
											</li>
										);
									})}
								</ul>
							</li>
						);
					})}
				</ol>
			)}
		</section>
	);
}
