<!--
	Mermaid.svelte - Client-side Mermaid diagram renderer
	======================================================

	WHY A SVELTE COMPONENT INSTEAD OF REMARK/REHYPE PLUGIN?

	Standard ```mermaid code blocks don't render as diagrams in mdsvex because:

	1. rehype-mermaid won't work with mdsvex + Shiki
		 - Shiki (syntax highlighter) processes code blocks BEFORE rehype plugins
		 - By the time rehype-mermaid runs, mermaid blocks are already transformed
		   into highlighted <pre><code> elements that the plugin can't recognize
		 - Reference: https://github.com/pngwn/MDsveX/issues/737

	2. mdsvex processes slot content as markdown
		 - Using <Mermaid>{code}</Mermaid> with slot children fails because
		   blank lines in mermaid code become paragraph breaks
		 - That's why we use a `code` prop instead: <Mermaid code={`...`} />

	USAGE IN MARKDOWN FILES:

	```svelte
	<script>
	import Mermaid from '$lib/components/Mermaid.svelte';
	</script>

	<Mermaid code={`
	flowchart LR
	    A[Source] --> B[Process] --> C[Output]
	`} />
	```

	NOTE: Curly braces in mermaid code will be interpreted as Svelte expressions.
	Either escape them or avoid using braces in labels.

	REFERENCES:
	- MDsveX + Mermaid issue: https://github.com/pngwn/MDsveX/issues/737
	- MDsveX plugin discussion: https://github.com/pngwn/MDsveX/discussions/354
	- Svelte Mermaid approach: https://jamesjoy.site/posts/2023-06-26-svelte-mermaidjs
-->
<script lang="ts">
	import { onMount } from 'svelte';

	let { code }: { code: string } = $props();

	let container: HTMLDivElement;
	let rendered = $state(false);
	let error = $state<string | null>(null);

	onMount(async () => {
		const mermaid = (await import('mermaid')).default;

		// Configure mermaid with terminal theme colors
		mermaid.initialize({
			startOnLoad: false,
			theme: 'dark',
			themeVariables: {
				// Background
				background: '#1a1a1a',
				mainBkg: '#2d2d2d',
				secondaryBkg: '#353535',

				// Text
				primaryTextColor: '#e5e5e5',
				secondaryTextColor: '#888888',
				tertiaryTextColor: '#666666',

				// Borders & lines
				primaryBorderColor: '#404040',
				lineColor: '#888888',

				// Accent colors (matching terminal theme)
				primaryColor: '#da7756', // orange
				secondaryColor: '#6b9eff', // blue
				tertiaryColor: '#2d2d2d',

				// Node colors
				nodeBorder: '#404040',
				clusterBkg: '#2d2d2d',
				clusterBorder: '#404040',

				// Flowchart specific
				edgeLabelBackground: '#2d2d2d',

				// Fonts
				fontFamily: 'JetBrains Mono, monospace',
				fontSize: '14px'
			},
			flowchart: {
				htmlLabels: true,
				curve: 'basis'
			},
			securityLevel: 'loose'
		});

		try {
			const trimmedCode = code?.trim();

			if (!trimmedCode) {
				error = 'No mermaid code provided';
				return;
			}

			// Generate unique ID for this diagram
			const id = `mermaid-${Math.random().toString(36).substring(2, 9)}`;

			// Render the diagram
			// Note: mermaid.render returns trusted SVG from our own markdown content
			// This is safe as the input is author-controlled content, not user input
			const { svg } = await mermaid.render(id, trimmedCode);

			// Replace container content with rendered SVG
			// Safe: SVG is generated by mermaid.js from author's markdown, not external user input
			container.innerHTML = svg;
			rendered = true;
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to render diagram';
			console.error('Mermaid render error:', err);
		}
	});
</script>

<div class="mermaid-wrapper" class:rendered class:error={!!error}>
	{#if error}
		<div class="mermaid-error">
			<span class="error-icon">⚠</span>
			<span class="error-text">Diagram error: {error}</span>
		</div>
	{/if}

	<div bind:this={container} class="mermaid-container">
		{#if !rendered && !error}
			<span class="loading-text">Loading diagram...</span>
		{/if}
	</div>
</div>

<style>
	.mermaid-wrapper {
		margin: 1.5rem 0;
		padding: 1rem;
		border: 1px solid var(--border);
		border-radius: 0.375rem;
		background-color: var(--bg-secondary);
		overflow-x: auto;
	}

	.mermaid-container {
		display: flex;
		justify-content: center;
		min-height: 100px;
	}

	/* Hide raw text once rendered */
	.mermaid-wrapper.rendered .mermaid-container {
		min-height: auto;
	}

	.loading-text {
		color: var(--text-muted);
		font-size: 0.875rem;
		font-style: italic;
	}

	/* Error state */
	.mermaid-error {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		padding: 0.75rem;
		background-color: rgba(224, 108, 117, 0.1);
		border: 1px solid var(--accent-red);
		border-radius: 0.25rem;
		margin-bottom: 1rem;
	}

	.error-icon {
		color: var(--accent-red);
	}

	.error-text {
		color: var(--accent-red);
		font-size: 0.875rem;
	}

	/* Style the rendered SVG */
	.mermaid-wrapper :global(svg) {
		max-width: 100%;
		height: auto;
	}

	/* Override mermaid default styles for better terminal look */
	.mermaid-wrapper :global(.nodeLabel) {
		font-family: 'JetBrains Mono', monospace;
	}

	.mermaid-wrapper :global(.edgeLabel) {
		font-family: 'JetBrains Mono', monospace;
		background-color: var(--bg-secondary) !important;
	}
</style>
