<script lang="ts">
	/**
	 * SocialFeedPage — the /feed hub. Renders the sanitized campaign feed
	 * (src/lib/data/social-feed.json, generated by scripts/snapshot-social.ts)
	 * as campaign cards. All cross-links are computed at build (ADR-053
	 * Phase 6 / social-hub H4): entries link to the live platform posts, and a
	 * campaign with a matching published post links to the blog.
	 */
	import { SITE_URL } from '$lib/seo';

	interface FeedEntry {
		post_id: string;
		date: string;
		platform: string;
		lang: string;
		format: string;
		topic: string;
		url: string;
		is_canonical: boolean;
	}

	interface FeedCampaign {
		cluster_id: string | null;
		canonical_url: string | null;
		blog_slug: string | null;
		topic: string;
		date: string;
		entries: FeedEntry[];
	}

	let { campaigns }: { campaigns: FeedCampaign[] } = $props();

	const PLATFORM_LABEL: Record<string, string> = {
		linkedin: 'LinkedIn',
		x: 'X',
		threads: 'Threads',
		mastodon: 'Mastodon',
		bluesky: 'Bluesky',
	};

	function entryLabel(entry: FeedEntry): string {
		const platform = PLATFORM_LABEL[entry.platform] ?? entry.platform;
		if (entry.platform === 'x' && entry.post_id.endsWith('-x-article')) {
			return 'X Article';
		}
		if (entry.format === 'thread') return `${platform} thread`;
		return platform;
	}
</script>

<svelte:head>
	<title>Feed | Brandon Wie</title>
	<meta
		name="description"
		content="Where each idea went — blog posts, X Articles, and LinkedIn posts grouped by campaign."
	/>
	<link rel="canonical" href={`${SITE_URL}/feed`} />
</svelte:head>

<main id="main-content" class="feed">
	<header class="feed__head">
		<div class="crumb">~/feed</div>
		<h1 class="feed__title">Social feed</h1>
		<p class="feed__lede">
			Where each idea went. One campaign, several surfaces — the long-form canonical plus the posts
			that point at it. Links are computed at build from the publishing archive.
		</p>
	</header>

	{#if campaigns.length === 0}
		<p class="feed__empty">Nothing published yet.</p>
	{:else}
		<ol class="feed__list">
			{#each campaigns as campaign (campaign.cluster_id ?? campaign.entries[0].post_id)}
				<li class="campaign">
					<div class="campaign__meta">
						<time datetime={campaign.date}>{campaign.date}</time>
						{#if campaign.cluster_id}
							<span class="campaign__id">{campaign.cluster_id}</span>
						{/if}
					</div>
					<h2 class="campaign__topic">{campaign.topic}</h2>
					<ul class="campaign__links">
						{#if campaign.blog_slug}
							<li>
								<a class="chip chip--blog" href={`/posts/${campaign.blog_slug}`}>Blog post</a>
							</li>
						{/if}
						{#each campaign.entries as entry (entry.post_id + entry.platform + entry.lang)}
							<li>
								<a
									class="chip"
									class:chip--canonical={entry.is_canonical}
									href={entry.url}
									target="_blank"
									rel="noopener noreferrer"
								>
									{entryLabel(entry)}{entry.lang !== 'en' ? ` (${entry.lang})` : ''}
								</a>
							</li>
						{/each}
					</ul>
				</li>
			{/each}
		</ol>
	{/if}
</main>

<style>
	.feed {
		max-width: 44rem;
		margin: 0 auto;
		padding: 40px 1.5rem 64px;
	}
	.feed__head {
		margin-bottom: 32px;
	}
	.crumb {
		font-family: var(--font-mono);
		font-size: 12px;
		color: var(--faint);
	}
	.feed__title {
		margin-top: 8px;
		font-family: var(--font-sans);
		font-size: 28px;
		font-weight: 700;
		color: var(--ink);
	}
	.feed__lede {
		margin-top: 8px;
		font-size: 14px;
		line-height: 1.6;
		color: var(--muted);
	}
	.feed__empty {
		font-family: var(--font-mono);
		font-size: 13px;
		color: var(--faint);
	}
	.feed__list {
		display: flex;
		flex-direction: column;
		gap: 16px;
		margin: 0;
		padding: 0;
		list-style: none;
	}
	.campaign {
		padding: 16px 18px;
		border: 1px solid var(--line2);
		border-radius: 12px;
		background: color-mix(in srgb, var(--panel) 45%, transparent);
	}
	.campaign__meta {
		display: flex;
		gap: 10px;
		align-items: center;
		font-family: var(--font-mono);
		font-size: 11px;
		color: var(--faint);
	}
	.campaign__id {
		color: var(--iris);
	}
	.campaign__topic {
		margin-top: 6px;
		font-family: var(--font-sans);
		font-size: 17px;
		font-weight: 600;
		line-height: 1.3;
		color: var(--ink);
	}
	.campaign__links {
		display: flex;
		flex-wrap: wrap;
		gap: 8px;
		margin: 12px 0 0;
		padding: 0;
		list-style: none;
	}
	.chip {
		display: inline-block;
		padding: 4px 10px;
		border: 1px solid var(--line2);
		border-radius: 999px;
		font-family: var(--font-mono);
		font-size: 12px;
		color: var(--muted);
		text-decoration: none;
		transition:
			border-color 0.2s,
			color 0.2s;
	}
	.chip:hover {
		border-color: var(--foam);
		color: var(--foam);
	}
	.chip--canonical {
		border-color: color-mix(in srgb, var(--gold) 55%, transparent);
		color: var(--gold);
	}
	.chip--blog {
		border-color: color-mix(in srgb, var(--iris) 55%, transparent);
		color: var(--iris);
	}
</style>
